// Code generated by hero.
// source: /home/maadi/workspace/goilerplate/views/admin/aside.html
// DO NOT EDIT!
package adminview

type Submenu struct {
	EnName string
	FaName string
	Icon   string
	Url    string
}
type Menu struct {
	EnName    string
	FaName    string
	Icon      string
	Submenues []Submenu
}

var menuList = []Menu{
	Menu{
		EnName: "users",
		FaName: "کاربران",
		Icon:   "nav-icon fa fa-dashboard",
		Submenues: []Submenu{
			Submenu{
				EnName: "addUser",
				FaName: "افزودن کاربر",
				Icon:   "nav-icon fa fa-circle-o",
				Url:    "/accounts/create",
			},
			Submenu{
				EnName: "usersList",
				FaName: "لیست کاربران",
				Icon:   "nav-icon fa fa-circle-o",
				Url:    "/accounts",
			},
			Submenu{
				EnName: "addGroup",
				FaName: "افزودن گروه کاربری",
				Icon:   "nav-icon fa fa-circle-o",
				Url:    "/groups/create",
			},
			Submenu{
				EnName: "groupList",
				FaName: "لیست گروه‌های کاربری",
				Icon:   "nav-icon fa fa-circle-o",
				Url:    "/groups",
			},
		},
	},
}

func Equal(a, b string) bool {
	return a == b
}
