database:
  name: postgres
  # Notice you must set order of properties exactly like this 
  url: host=localhost port=5432 user=goldfish password=goldfish dbname=goldfish
  test: host=localhost port=5432 user=goldfish password=goldfish dbname=goldfish_test
  admin: host=localhost port=5432 user=postgres password=postgres dbname=postgres

static: ./static/

jwt:
  secret: <JWT-SECRET>
  algorithm: HS256
  max_age: 900  # 15 minute
  httponly: true
  refresh_token:
    secret: <JWT-REFRESH-SECRET>
    algorithm: HS256
    max_age: 86400  # 24 hour
    secure: true
    httponly: true
    path: /

ports:
  https: 8443
  http: 8000

tls:
  crt: ./server.crt
  key: ./server.key

domain-name: 192.168.1.7


# It is recommended to use a key with 32 or 64 bytes.
secret-key: g9!8(2w0(n%lAmhw

# valid length are 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256.
block-secret-key: q!~329ptQRE)9G~4

